name: Build & deploy

on:
  push:
    branches:
      - ega-hall
  pull_request:
    branches:
      - ega-hall

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Installing Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Installing NPM packages
        run: npm ci

      - name: Building project
        run: npm run build

      - name: Uploading production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist

      - name: copy file to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: ./dist/*
          target: /var/www/egahall.kg/egaSite/
  # deploy:
  #   name: Deploy
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/ega-hall'

  #   steps:
  #     - name: Downloading artifact
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: production-files
  #         path: ./dist

  #     - name: Deploying to gh-pages
  #       uses: peaceiris/actions-gh-pages@v3
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: ./dist